vulnerability_check: false
allow_licenses:
  - '0BSD'
  - 'Apache-2.0'
  - 'Artistic-2.0'
  - 'BlueOak-1.0.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'CC-BY-4.0'
  - 'CC0-1.0'
  - 'ISC'
  - 'MIT'
  - 'Python-2.0'
  - 'Unlicense'
allow-dependencies-licenses:
  - 'pkg:npm/thingies@1.21.0' #  MIT and Unlicense
