environment:
  matrix:
    - nodejs_version: "6"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@~5.6.0
  - npm install
  - choco install googlechrome

test_script:
  - node --version
  - npm --version
  - npm run test:packages
  - npm run test:cli
  - node tests\run_e2e.js --appveyor "--glob=tests/{basic,commands,generate,build/styles}/**"

build: off

cache:
  - node_modules -> package-lock.json
