environment:
  matrix:
  - nodejs_version: "6.0"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test
  - node tests\run_e2e.js

build: off
