dist: trusty
sudo: required
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  matrix:
    - NODE_VERSION=5 SCRIPT=lint
    - NODE_VERSION=5 SCRIPT=test
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      env: NODE_VERSION=5 SCRIPT=lint

script:
  - npm run-script $SCRIPT

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ~/.nvm/nvm-exec; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/cask; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome --force; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false
install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional
