dist: trusty
sudo: false

addons:
  chrome: stable

language: node_js

cache:
  directories:
     - ./node_modules

matrix:
  fast_finish: true
  allow_failures:
    - env: nightly
    - env: ng2
    - node_js: "7"
    - node_js: "8"
  include:
    - stage: build
      script: npm run lint
      env: lint
    - script: npm run build
      env: build

    - stage: test
      script: npm run test
      env: test
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nb-shards=4 --shard=0 --nosilent
      env: e2e-0
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nb-shards=4 --shard=1 --nosilent
      env: e2e-1
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nb-shards=4 --shard=2 --nosilent
      env: e2e-2
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nb-shards=4 --shard=3 --nosilent
      env: e2e-3
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --eject "--glob=tests/build/**"
      env: eject

    # Optional builds.
    - node_js: "6"
      os: linux
      before_script: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
      script: node tests/run_e2e.js --ng2 "--glob=tests/{build,test,misc}/**"
      env: ng2
    - node_js: "6"
      os: linux
      before_script: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
      script: node tests/run_e2e.js "--nightly --glob=tests/{build,test,misc}/**"
      env: nightly
    - node_js: "7"
      os: linux
      before_script: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
      script: node tests/run_e2e.js "--glob=tests/{build,test,misc}/**"
      env: node7
    - node_js: "8"
      os: linux
      before_script: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
      script: node tests/run_e2e.js "--glob=tests/build/**"
      env: node8

    - stage: deploy
      script: skip
      env: builds
      deploy:
      - provider: script
        script: node scripts/git-builds.js
        skip_cleanup: true
        on:
          all_branches: true
    - stage: deploy
      script: skip
      env: publish
      deploy:
      - provider: script
        script: node scripts/publish/publish.js
        skip_cleanup: true
        on:
          tags: true


before_install:
  # Install npm 5.
  - npm install -g npm@~5.3.0

install:
  - npm install

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    # GITHUB_ACCESS_TOKEN=<github token, a personal access token of the angular-builds account, account access in valentine>
    # This is needed to publish packages to github for continuous packages delivery.
    - secure: "XUM1RCN/ZH34ju2PI9eHPRMnSlbj45XcBx/ZnZ13wfau60iJCveU7Ded8SC8uwGDp58rGGePXyJfh5l5dAnIWbSAGNKlrEgGTr41RSCbyzrV6m4lAcwNzUo/PkKum1vAApk21PqscrSSWOBAOC3nMCln25GLzgUMm6G8FBOc599NuszcoQvru+H+4JthSHn4l/nmeTZDs2oCBvwnmng/78rEW5CXvJEpAwuaaZLvzzIFdoZu+SuceYvGnL5xHo0ppPF/0NYzZlb7KBKREp44Lq1lOKlDtH5wqjEi7b2aA7/GnesOgLUBmbbSVUzmCxs6PtzGhD56aiL2Qtu8c4LZyvNfzPXSLbx8ljYmdytHkio9w3377wWFRXJDfIsgv9JKHxxyA0T34yzQkqWbgWKPMgJ3om+lb875iXAtXfNyS0trnN+rwLZZtFxygjHyx8IWY+NZD5i5fyjMdFyetNxbHe3ktI73nY+Tl6hDqJXvN8WwQlMovLNUMcY4wGUoPooLka9L+94uetbf3U4KVgshrLHI59jMZsO0qrDGsCZMubHEy80acrNkCTi/uGIbVR0KF94z81VF+S7edYv80AkQTRijpgNV34045L/IqSHgbueozRgVFj2arkAGGFjLlZJifmsRC/Eq1ZWkKsKY/1NusKssCRtycJQjeLOW0qV1T0w="
    # NPM_TOKEN used for deployment.
    - secure: "QDefZm9p3/SQ6ts0WVkzwr1qv4tvxpu5hB5ptTGQwRP02oPQumebE+uazSjhrbMf9zCnlrQSaCV7VxMdqQ0GUdAQ+gZz4mr/6SyT1eThTfgqq4GFX24M5dlcWW4rB6ot5NICPnsvASBVDn4IkapTY135/s5fqp2TeDJmAH8xMxKRbsG/b4+KCvhjpO7WJMZumkrwsWFrtAh1zFjrXoHwEySYPkwZceJmSi7GPmjZLodMmSkMxi4vuOAgrx6kWPTuCszKGXm7+Y1UbjeSSoBYLt2c19oy2dJKrER9sSx8/1yeV1C2JJ/cabYBktcn1svUh0lo1j1YOWtEXaIv7SRU694EtWxiuaL8iIcABHdoaLt/BZ34MLG0RdvFu0i2Bv5HxGWQg5TB/Jy502dqkep5ILofF80Ya9NTeapIPSbI3IEWcsCCw+t0pv/91XXU7mduDwtvBtzwxC4nKS4PITjrFTSrsr0wiLagW6ZCbKMrUitEFgedvsa3Tf8wVtt1s/Z7W2iLt81TTVdCei+46PtLIG3k9R1J78WmPLsGJ3uMXo/Cgc7q5PN66Dx6V1RZMBbS9xG0OPxd8a/6Lj94u6QWS1x50osVPEqUqGmT2tWP5fabrDKLUnVLm2Y0O1eBnnu9ew+ccCKou0FCqlx5ppRekBIaMibHbmgahRLMgNbaJR0="


