dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
  - "6"
os:
  - linux
  - osx
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  matrix:
    - SCRIPT=lint
    - SCRIPT=test
#    - TARGET=mobile SCRIPT=mobile_test
matrix:
  exclude:
    - node_js: "6"
      env: SCRIPT=lint
    - os: osx
      node_js: "5"
      env: SCRIPT=lint
#    - os: osx
#      env: TARGET=mobile SCRIPT=mobile_test

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/cask; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome --force; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi
  - if [[ "$TARGET" == "mobile" ]]; then export MOBILE_TEST=true; fi
  - npm config set spin false
  - npm config set progress false

install:
  - npm install --no-optional

script:
  - npm run-script $SCRIPT