version: 2

_defaults: &defaults
  working_directory: ~/ng
  docker:
    - image: angular/ngcontainer

_post_checkout: &post_checkout
  post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install
      - run: npm run lint

  commits:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install
      - run: npm run validate-commits

  test:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install
      - run: npm run test

  integration:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: angular_devkit-integration-simple-{{ .Branch }}-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/simple-app/package-lock.json" }}
      - restore_cache:
          key: angular_devkit-integration-aio-{{ .Branch }}-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/aio-app/package-lock.json" }}

      - run: npm install
      - run: xvfb-run -a npm run integration

      - save_cache:
          key: angular_devkit-integration-simple-{{ .Branch }}-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/simple-app/package-lock.json" }}
          paths:
            - "tests/@angular_devkit/build_optimizer/webpack/simple-app/node_modules"
      - save_cache:
          key: angular_devkit-integration-aio-{{ .Branch }}-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/aio-app/package-lock.json" }}
          paths:
            - "tests/@angular_devkit/build_optimizer/webpack/aio-app/node_modules"

  build:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: bazel run @io_bazel_rules_typescript_node//:bin/npm install
      - run: bazel build ...

      - save_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"


workflows:
  version: 2
  default_workflow:
    jobs:
      - lint
      - commits
      - build
      - test
      - integration
