version: 2

_defaults: &defaults
  working_directory: ~/ng
  docker:
    - image: angular/ngcontainer:0.1.0

_post_checkout: &post_checkout
  post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: npm install --no-save
      - run: npm run lint

  validate:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: npm install --no-save
      - run: npm run validate -- --ci

  test:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: npm install --no-save
      - run: npm run test -- --code-coverage --full

  integration:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: angular_devkit-integration-simple-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/simple-app/package-lock.json" }}
      - restore_cache:
          key: angular_devkit-integration-aio-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/aio-app/package-lock.json" }}

      - run: npm install --no-save
      - run: xvfb-run -a npm run integration

      - save_cache:
          key: angular_devkit-integration-simple-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/simple-app/package-lock.json" }}
          paths:
            - "tests/@angular_devkit/build_optimizer/webpack/simple-app/node_modules"
      - save_cache:
          key: angular_devkit-integration-aio-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/aio-app/package-lock.json" }}
          paths:
            - "tests/@angular_devkit/build_optimizer/webpack/aio-app/node_modules"

  build:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: bazel run @nodejs//:npm install
      - run: bazel build //packages/...
      - run: npm run admin -- build

      - save_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

  snapshot_publish:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: npm install --no-save
      - run:
          name: Decrypt Credentials
          command: |
            openssl aes-256-cbc -d -in .circleci/github_token -k "${KEY}" -out ~/github_token
      - run:
          name: Deployment to Snapshot
          command: |
            npm run admin -- snapshots --verbose --githubTokenFile=${HOME}/github_token

  publish:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: npm install --no-save
      - run:
          name: Decrypt Credentials
          command: |
            openssl aes-256-cbc -d -in .circleci/npm_token -k "${KEY}" -out ~/.npmrc
      - run:
          name: Deployment to NPM
          command: |
            npm run admin -- publish --verbose

workflows:
  version: 2
  default_workflow:
    jobs:
      - lint
      - validate
      - build:
          requires:
            - lint
            - validate
      - test:
          requires:
            - build
      - integration:
          requires:
            - build
      - snapshot_publish:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test
            - build
            - integration
            - snapshot_publish
          filters:
            tags:
              only: /^v\d+/
            branches:
              ignore: /.*/
