name: Feature request triage bot

# Declare default permissions as read only.
permissions:
  contents: read

on:
  schedule:
    # Run at 13:00 every day
    - cron: '0 13 * * *'

jobs:
  feature_triage:
    # To prevent this action from running in forks, we only run it if the repository is exactly the
    # angular/angular-cli repository.
    if: github.repository == 'angular/angular-cli'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/feature-request@2b0a3018401da50c0b34a4dedde2a6fdb9e90394
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
