name: Lock Inactive Issues

# Declare default permissions as read only.
permissions:
  contents: read

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@e60312a062a16756f631496ffcad2b7e78c0046d
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
