name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@58f0cf12a883367d5f369893b9a35d6e133cbefa
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
